// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiytO__urIWfAsXBFzWIEVzZV4hh_vPeo',
    appId: '1:515237415168:web:a8511ef6c6320a5dac4be5',
    messagingSenderId: '515237415168',
    projectId: 'faceshare-ai',
    authDomain: 'faceshare-ai.firebaseapp.com',
    storageBucket: 'faceshare-ai.firebasestorage.app',
    measurementId: 'G-N9RTLRVEDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxqjuGF0jwZ5qS0kFEhX32UoN2gPT-55Y',
    appId: '1:515237415168:android:bfc43532f66c738dac4be5',
    messagingSenderId: '515237415168',
    projectId: 'faceshare-ai',
    storageBucket: 'faceshare-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3NIBeI4iBMylp0Z3x9rAYsvss5Gut1B4',
    appId: '1:515237415168:ios:7013d804f7ebd204ac4be5',
    messagingSenderId: '515237415168',
    projectId: 'faceshare-ai',
    storageBucket: 'faceshare-ai.firebasestorage.app',
    iosBundleId: 'com.example.faceshareAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3NIBeI4iBMylp0Z3x9rAYsvss5Gut1B4',
    appId: '1:515237415168:ios:7013d804f7ebd204ac4be5',
    messagingSenderId: '515237415168',
    projectId: 'faceshare-ai',
    storageBucket: 'faceshare-ai.firebasestorage.app',
    iosBundleId: 'com.example.faceshareAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiytO__urIWfAsXBFzWIEVzZV4hh_vPeo',
    appId: '1:515237415168:web:eb99eb106cb6e3ccac4be5',
    messagingSenderId: '515237415168',
    projectId: 'faceshare-ai',
    authDomain: 'faceshare-ai.firebaseapp.com',
    storageBucket: 'faceshare-ai.firebasestorage.app',
    measurementId: 'G-R88EN7QQ4H',
  );
}
